
const LOAD_FORMS_SUCCESS = 'LOAD_FORMS_SUCCESS';
const CREATE_FORM_SUCCESS = 'CREATE_FORM_SUCCESS';
const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS';
const PREVIEW_FORM_SUCCESS = 'PREVIEW_FORM_SUCCESS';
const LOAD_FIELDS_SUCCESS = 'LOAD_FIELDS_SUCCESS';
const BEGIN_SERVER_CALL = 'BEGIN_SERVER_CALL';
const SERVER_CALL_ERROR = 'SERVER_CALL_ERROR';


export {
    LOAD_FORMS_SUCCESS,
    CREATE_FORM_SUCCESS,
    DELETE_FORM_SUCCESS,
    PREVIEW_FORM_SUCCESS,
    LOAD_FIELDS_SUCCESS,
    BEGIN_SERVER_CALL,
    SERVER_CALL_ERROR
};